### ISSUE TITLE
Import fails in Types due to role bonuses

### ISSUE THREAD

**Issue by MaraRinn** [MaraRinn/yamlloader#1]
```
Importing Types
Opening Yaml
Yaml Processed into memory
Type: 582, Skill: roleBonuses, Trait: {'bonus': 300, 'bonusText': {'ru': '…', 'fr': u'…', 'en': '…', 'zh': u'…', 'de': u'…', 'ja': u'…'}, 'importance': 1, 'unitID': 105}.
Traceback (most recent call last):
  File "./Load.py", line 47, in <module>
    types.importyaml(connection,metadata,sourcePath)
  File "…/yamlloader/tableloader/tableFunctions/types.py", line 57, in importyaml
    bonus=typeids[typeid]['traits'][skill][trait].get('bonus'),
TypeError: list indices must be integers, not dict
```

**Comment by MaraRinn** [comment]
Fuzzysteve reckons he has this sorted out already. Pull it in from upstream!

**Comment by MaraRinn** [comment]
Done.
